# Generated by Django 4.0.6 on 2023-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisherid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='pics')),
                ('city', models.CharField(max_length=255)),
                ('eventtype', models.IntegerField()),
            ],
        ),
    ]
