# Generated by Django 4.0.6 on 2023-02-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categoryid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
