# Generated by Django 4.0.6 on 2023-03-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_event_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField()),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=12)),
                ('duration', models.IntegerField()),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('contactno', models.CharField(max_length=16)),
                ('contactperson', models.CharField(max_length=64)),
                ('is_canceled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
