# Generated by Django 4.0.6 on 2023-03-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_eventdetail_eventprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('mobile', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField()),
                ('registeruser_id', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('detail', models.CharField(max_length=128)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
